service: go-app-gin

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  versionFunctions: false

package:
  individually: true

functions:
  api:
    handler: bootstrap
    package:
      artifact: bin/deployment.zip
    events:
      - http:
          path: /albums
          method: get
    environment:
      GIN_MODE: release
